version: '3.9'
services:
  postgres:
    image: postgres:14
    container_name: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: postgres
  pgweb:
    container_name: pgweb
    restart: always
    image: sosedoff/pgweb
    ports: 
      - 9000:8081
    links: 
      - postgres:postgres
    environment:
      PGWEB_DATABASE_URL: "postgres://postgres:postgres@host.docker.internal:5432/postgres?sslmode=disable"