# Fixes for https://github.com/aws-amplify/amplify-js/issues/7772
packageExtensions:
  "@mantine/styles@*":
    dependencies:
      "@emotion/cache": "*"
      "@emotion/serialize": "*"
      "@emotion/utils": "*"
  "vite@*":
    dependencies:
      "supports-color": "*"
  "@aws-amplify/auth@*":
    dependencies:
      "buffer": "*"
      "@aws-crypto/sha256-js": "*"
  "@aws-crypto/sha256-browser@*":
    dependencies:
      "@aws-sdk/util-utf8-browser": "*"